### PR TITLE
Welcome Center Scenes

### PR DESCRIPTION
**Pull request by connorescajeda**

### CODE REVIEW

**Comment by mgoadric** [comment]
I'm getting a crash and an error of "NameError: name 'tour' is not defined" from line 52 of wc.rpy.

**Comment by connorescajeda** [comment]
Has this request been merged in so far?

**Comment by mgoadric** [comment]
No, not yet, I was testing it before merging it.

**Comment by mgoadric** [comment]
Maybe my path of trying to make all the bad choices didn't get the tour variable defined? Should it be in the start section?

**Comment by connorescajeda** [comment]
That could be it, might try that and see what happens. I thought initialize it at the start of the file should take care of it but maybe Renpy is weird

**Pull request merged**
